name: NPM Audit Report - PR
'on':
  push:
    branches:
      - master
jobs:
  scan:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - name: Use Node.js '20.x'
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 22.x
      - name: Install libboost and sodium
        run: sudo apt-get install -y libboost-all-dev libsodium-dev
      - name: install dependencies
        run: npm ci
      - uses: oke-py/npm-audit-action@v3.0.0
        with:
          audit_level: moderate
          github_token: '${{ secrets.GITHUB_TOKEN }}'
          issue_assignees: 'thecomputergenie'
          issue_labels: 'vulnerability,test'
          dedupe_issues: true
          create_pr_comments: true
